import { StateNode } from "../state-node";
import { mockVdom2 } from "./vdom.mock2";

test("preOrderTraversal", () => {
    const state = mockVdom2();

    const order = StateNode.preOrderTraversal(state.root);
    expect(order.length).toBe(41);
    expect(order[0]).toBe(state.root);
    expect(order[1]).toBe(state.paragraph1);
    expect(order[2]).toBe(state.span1);
    expect(order[3]).toBe(state.span2);
    expect(order[4]).toBe(state.span3);
    expect(order[5]).toBe(state.paragraph2);
    expect(order[6]).toBe(state.span4);
    expect(order[7]).toBe(state.nestedParagraph1);
    expect(order[8]).toBe(state.span5);
    expect(order[9]).toBe(state.span6);
    expect(order[10]).toBe(state.nestedParagraph2);
    expect(order[11]).toBe(state.span7);
    expect(order[12]).toBe(state.span8);
    expect(order[13]).toBe(state.paragraph3);
    expect(order[14]).toBe(state.span9);
    expect(order[15]).toBe(state.span9Child1);
    expect(order[16]).toBe(state.span9Child2);
    expect(order[17]).toBe(state.span10);
    expect(order[18]).toBe(state.span10Child1);
    expect(order[19]).toBe(state.span10Child2);
    expect(order[20]).toBe(state.span10Child2Nested1);
    expect(order[21]).toBe(state.span10Child2Nested2);
    expect(order[22]).toBe(state.nestedParagraph3);
    expect(order[23]).toBe(state.span11);
    expect(order[24]).toBe(state.span12);
    expect(order[25]).toBe(state.deepNestedParagraph1);
    expect(order[26]).toBe(state.span13);
    expect(order[27]).toBe(state.span14);
    expect(order[28]).toBe(state.paragraph4);
    expect(order[29]).toBe(state.span15);
    expect(order[30]).toBe(state.span16);
    expect(order[31]).toBe(state.nestedParagraph4);
    expect(order[32]).toBe(state.span17);
    expect(order[33]).toBe(state.span18);
    expect(order[34]).toBe(state.deeperNestedParagraph);
    expect(order[35]).toBe(state.span19);
    expect(order[36]).toBe(state.span20);
    expect(order[37]).toBe(state.paragraph5);
    expect(order[38]).toBe(state.span21);
    expect(order[39]).toBe(state.span22);
    expect(order[40]).toBe(state.span23);
});