import { VDomNode } from "../vdom-node";
import { mockVdom2 } from "./vdom.mock2.spec";
import { VDomTraversal } from "../vdom-traversal";

test("preOrderTraversal", () => {
    const vdomNode = mockVdom2();

    const order = VDomTraversal.preOrderTraversal(vdomNode.root);
    expect(order.length).toBe(41);
    expect(order[0]).toBe(vdomNode.root);
    expect(order[1]).toBe(vdomNode.paragraph1);
    expect(order[2]).toBe(vdomNode.span1);
    expect(order[3]).toBe(vdomNode.span2);
    expect(order[4]).toBe(vdomNode.span3);
    expect(order[5]).toBe(vdomNode.paragraph2);
    expect(order[6]).toBe(vdomNode.span4);
    expect(order[7]).toBe(vdomNode.nestedParagraph1);
    expect(order[8]).toBe(vdomNode.span5);
    expect(order[9]).toBe(vdomNode.span6);
    expect(order[10]).toBe(vdomNode.nestedParagraph2);
    expect(order[11]).toBe(vdomNode.span7);
    expect(order[12]).toBe(vdomNode.span8);
    expect(order[13]).toBe(vdomNode.paragraph3);
    expect(order[14]).toBe(vdomNode.span9);
    expect(order[15]).toBe(vdomNode.span9Child1);
    expect(order[16]).toBe(vdomNode.span9Child2);
    expect(order[17]).toBe(vdomNode.span10);
    expect(order[18]).toBe(vdomNode.span10Child1);
    expect(order[19]).toBe(vdomNode.span10Child2);
    expect(order[20]).toBe(vdomNode.span10Child2Nested1);
    expect(order[21]).toBe(vdomNode.span10Child2Nested2);
    expect(order[22]).toBe(vdomNode.nestedParagraph3);
    expect(order[23]).toBe(vdomNode.span11);
    expect(order[24]).toBe(vdomNode.span12);
    expect(order[25]).toBe(vdomNode.deepNestedParagraph1);
    expect(order[26]).toBe(vdomNode.span13);
    expect(order[27]).toBe(vdomNode.span14);
    expect(order[28]).toBe(vdomNode.paragraph4);
    expect(order[29]).toBe(vdomNode.span15);
    expect(order[30]).toBe(vdomNode.span16);
    expect(order[31]).toBe(vdomNode.nestedParagraph4);
    expect(order[32]).toBe(vdomNode.span17);
    expect(order[33]).toBe(vdomNode.span18);
    expect(order[34]).toBe(vdomNode.deeperNestedParagraph);
    expect(order[35]).toBe(vdomNode.span19);
    expect(order[36]).toBe(vdomNode.span20);
    expect(order[37]).toBe(vdomNode.paragraph5);
    expect(order[38]).toBe(vdomNode.span21);
    expect(order[39]).toBe(vdomNode.span22);
    expect(order[40]).toBe(vdomNode.span23);
});
